version: '2'

#############
# Services
#############
services:
    server:
        container_name: php7_server
        build: ./server
        volumes_from:
            - volume_www
        tty: true
        networks:
            www_net:
                ipv4_address: 172.29.0.105

    nginx:
        build: ./nginx
        volumes_from:
            - volume_www
        volumes:
            - ./logs/nginx/:/var/log/nginx 
        networks:
            www_net:
                ipv4_address: 172.29.0.101
        ports:
            - "80"
            - "443"
        links:
            - php-fpm

    memcached:
        build: ./memcached
        volumes_from:
            - volume_data
        volumes:
            - ./logs/memcached/:/var/log/memcached
        networks:
            www_net:
                ipv4_address: 172.29.0.102
        ports:
            - "11211"
        links:
            - php-fpm

    redis:
            build: ./redis
            volumes_from:
               - volume_data
            ports:
               - "6379"
            networks:
                www_net:
                    ipv4_address: 172.29.0.104

    php-fpm:
        build: ./php-fpm
        volumes_from:
            - volume_www
        networks:
            www_net:
                ipv4_address: 172.29.0.103
        expose:
            - "9000"
        links:
            - server


#################
##   Volumes
#################

    volume_www:
        build: ./volume
        volumes: 
            - ./www:/var/www
    volume_data:
        build: ./data
        volumes:
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data

#################
##   Network
#################
networks:
    www_net:
        driver: bridge
        ipam:
          config:
          - subnet: 172.29.0.0/24
